[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "brs"
authors = [{name = "Jay Besch", email = "jay.besch@uspto.gov"}]
dynamic = ["version", "description"]
